spring.application.name=dohis-backend
logging.level.org.springframework.security=DEBUG


server.port=8080

spring.data.mongodb.uri=${MONGODB_URI}
app.jwt.expires-minutes=120
app.jwt.secret=${JWT_SECRET}
app.jwt.issuer=DOHIS
app.jwt.expiresInMinutes=120

app.google.clientSecret=${GOOGLE_CLIENT_SECRET}
app.google.clientId=${GOOGLE_CLIENT_ID}
app.google.redirectUri=${GOOGLE_REDIRECT_URI}
app.google.owner.refreshToken=${GOOGLE_OWNER_REFRESH_TOKEN}

app.drive.rootFolderId=${GOOGLE_DRIVE_ROOT_FOLDER_ID}
app.drive.reportsFolderId=${GOOGLE_DRIVE_REPORTS_FOLDER_ID}

app.google.scopes=https://www.googleapis.com/auth/drive,https://www.googleapis.com/auth/userinfo.email,openid

app.jwt.defaultMinutes=1440
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}